#!/usr/bin/env python3
"""Emit the compile/run classpath for a Minecraft instance, taken from its version JSON.

Why this exists
---------------
The project previously compiled against hand-written API stubs generated by
`scripts/generate_stubs.py`. That let code compile against an API that did not exist and then fail
at runtime. It caused three separate multi-hour debugging rounds:

  1. mixin targets naming `net.minecraft.class_XXXX` (intermediary) in a named-mappings build
  2. `@Retention(CLASS)` on `@Inject`/`@Accessor` stubs, so Mixin could not see the annotations
  3. `RenderTarget.resize(int,int,boolean)`, `Window.getFramebufferWidth()`,
     `Minecraft.getMainRenderTarget()` and `Minecraft.resizeDisplay()` - none of which exist

Compiling against the real client jar means javac checks every Minecraft API call, and the stub
gap disappears entirely. No Loom required: the client jar plus the launcher's libraries are enough.

Usage:
    build_classpath.py <instance-dir>        # prints a ':'-joined classpath

`<instance-dir>` is a directory under `<minecraft>/versions/<name>/` containing `<name>.jar` and
`<name>.json`.
"""
import json
import os
import sys


def maven_path(coordinates):
    """Turn "group:artifact:version" into "group/path/artifact/version/artifact-version.jar"."""
    parts = coordinates.split(":")
    if len(parts) < 3:
        return None
    group, artifact, version = parts[0], parts[1], parts[2]
    if not group or not artifact or not version:
        return None
    return "/".join(group.split(".") + [artifact, version, f"{artifact}-{version}.jar"])


def find_libraries_root(instance_dir):
    """Walk up from the instance dir until a sibling 'libraries' directory is found."""
    current = os.path.abspath(instance_dir)
    for _ in range(5):
        candidate = os.path.join(current, "libraries")
        if os.path.isdir(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return None


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    instance_dir = os.path.abspath(sys.argv[1])
    if not os.path.isdir(instance_dir):
        print(f"error: not a directory: {instance_dir}", file=sys.stderr)
        return 1

    name = os.path.basename(instance_dir.rstrip("/"))
    version_json = os.path.join(instance_dir, name + ".json")
    client_jar = os.path.join(instance_dir, name + ".jar")

    if not os.path.isfile(version_json):
        print(f"error: version JSON not found: {version_json}", file=sys.stderr)
        return 1
    if not os.path.isfile(client_jar):
        print(f"error: client jar not found: {client_jar}", file=sys.stderr)
        return 1

    libraries_root = find_libraries_root(instance_dir)
    if libraries_root is None:
        print("error: could not locate the 'libraries' directory above "
              f"{instance_dir}", file=sys.stderr)
        return 1

    entries = [client_jar]
    missing = []
    with open(version_json, "r", encoding="utf-8") as handle:
        data = json.load(handle)

    # Fabric's version JSON splits the loader's own libraries into `patches`. Without these the
    # mixin annotations and ClientModInitializer are missing, so both must be collected.
    declared = list(data.get("libraries", []))
    for patch in data.get("patches", []):
        declared.extend(patch.get("libraries", []))

    for library in declared:
        artifact = library.get("downloads", {}).get("artifact", {})
        path = artifact.get("path")
        if not path:
            # Fabric's loader libraries are declared as bare Maven coordinates
            # ("group:artifact:version") with no downloads block, so derive the standard
            # repository layout from the name.
            path = maven_path(library.get("name", ""))
        if not path:
            continue
        full = os.path.join(libraries_root, path)
        if os.path.isfile(full):
            entries.append(full)
        else:
            missing.append(path)

    # Mods in the instance are compile-time dependencies too (Mod Menu, Sodium, Fabric API).
    mods_dir = os.path.join(instance_dir, "mods")
    if os.path.isdir(mods_dir):
        for name in sorted(os.listdir(mods_dir)):
            if name.endswith(".jar"):
                entries.append(os.path.join(mods_dir, name))

    if missing:
        # Not fatal: native-only or platform-excluded artifacts are legitimately absent.
        print(f"note: {len(missing)} declared libraries are not present on disk "
              f"(e.g. {missing[0]})", file=sys.stderr)

    print(":".join(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
