#!/bin/bash
# Dumps the exact signatures a Metal backend must implement, straight from the real client jar.
# Regenerate after any Minecraft update:  ./scripts/dump_backend_api.sh > docs/backend-api.md
set -euo pipefail
INST="${METALMOD_MC_INSTANCE:-$HOME/Documents/.minecraft/versions/MetalMod_Test_26.2}"
NAME="$(basename "$INST")"
JAR="$INST/$NAME.jar"
JAVAP="${JAVA_HOME:-/Library/Java/JavaVirtualMachines/jdk-26.jdk/Contents/Home}/bin/javap"

CLASSES=(
  com.mojang.blaze3d.systems.GpuBackend
  com.mojang.blaze3d.systems.GpuDeviceBackend
  com.mojang.blaze3d.systems.CommandEncoderBackend
  com.mojang.blaze3d.systems.RenderPassBackend
  com.mojang.blaze3d.systems.GpuSurfaceBackend
  com.mojang.blaze3d.systems.GpuSurface
  com.mojang.blaze3d.systems.GpuSurface\$Configuration
  com.mojang.blaze3d.systems.GpuSurface\$PresentMode
  com.mojang.blaze3d.systems.CommandEncoder
  com.mojang.blaze3d.systems.RenderPass
  com.mojang.blaze3d.systems.RenderPass\$RenderArea
  com.mojang.blaze3d.systems.RenderPassDescriptor
  com.mojang.blaze3d.systems.RenderPassDescriptor\$Attachment
  com.mojang.blaze3d.systems.DeviceInfo
  com.mojang.blaze3d.systems.DeviceLimits
  com.mojang.blaze3d.systems.DeviceFeatures
  com.mojang.blaze3d.systems.GpuQueryPool
  com.mojang.blaze3d.systems.BackendCreationException
  com.mojang.blaze3d.systems.BackendCreationException\$Reason
  com.mojang.blaze3d.GLFWErrorCapture\$Error
  com.mojang.blaze3d.GpuFormat
  com.mojang.blaze3d.textures.GpuTexture
  com.mojang.blaze3d.textures.GpuTextureView
  com.mojang.blaze3d.textures.GpuSampler
  com.mojang.blaze3d.textures.AddressMode
  com.mojang.blaze3d.textures.FilterMode
  com.mojang.blaze3d.buffers.GpuBuffer
  com.mojang.blaze3d.buffers.GpuBuffer\$Usage
  com.mojang.blaze3d.buffers.GpuFence
  com.mojang.blaze3d.pipeline.CompiledRenderPipeline
  com.mojang.blaze3d.pipeline.RenderPipeline
  com.mojang.blaze3d.shaders.ShaderSource
  com.mojang.blaze3d.shaders.ShaderType
  com.mojang.blaze3d.shaders.GpuDebugOptions
  net.minecraft.client.PreferredGraphicsApi
)

echo "# Metal backend API contract"
echo
echo "Generated by \`scripts/dump_backend_api.sh\` from \`$NAME.jar\`."
echo "Do not edit by hand - regenerate after a Minecraft update and diff."
echo
for c in "${CLASSES[@]}"; do
  echo "## \`${c//\\\$/\$}\`"
  echo
  echo '```java'
  "$JAVAP" -cp "$JAR" -p "$c" 2>/dev/null || echo "// NOT FOUND in this build"
  echo '```'
  echo
done
